//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.28 at 12:47:45 PM GMT+05:00 
//


package com.webex.schemas._2002._06.service.meeting.auo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webex.schemas._2002._06.service.meeting.auo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webex.schemas._2002._06.service.meeting.auo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AudioOnlyType }
     * 
     */
    public AudioOnlyType createAudioOnlyType() {
        return new AudioOnlyType();
    }

    /**
     * Create an instance of {@link RepeatType.DayInWeek }
     * 
     */
    public RepeatType.DayInWeek createRepeatTypeDayInWeek() {
        return new RepeatType.DayInWeek();
    }

    /**
     * Create an instance of {@link CreateTeleconferenceSession }
     * 
     */
    public CreateTeleconferenceSession createCreateTeleconferenceSession() {
        return new CreateTeleconferenceSession();
    }

    /**
     * Create an instance of {@link RemindType }
     * 
     */
    public RemindType createRemindType() {
        return new RemindType();
    }

    /**
     * Create an instance of {@link GetTeleconferenceSessionResponse }
     * 
     */
    public GetTeleconferenceSessionResponse createGetTeleconferenceSessionResponse() {
        return new GetTeleconferenceSessionResponse();
    }

    /**
     * Create an instance of {@link TelephonyType }
     * 
     */
    public TelephonyType createTelephonyType() {
        return new TelephonyType();
    }

    /**
     * Create an instance of {@link AudioOnlyType.FullAccessAttendees }
     * 
     */
    public AudioOnlyType.FullAccessAttendees createAudioOnlyTypeFullAccessAttendees() {
        return new AudioOnlyType.FullAccessAttendees();
    }

    /**
     * Create an instance of {@link AudioOnlyInstanceType.FullAccessAttendees }
     * 
     */
    public AudioOnlyInstanceType.FullAccessAttendees createAudioOnlyInstanceTypeFullAccessAttendees() {
        return new AudioOnlyInstanceType.FullAccessAttendees();
    }

    /**
     * Create an instance of {@link AudioOnlyType.LimitedAccessAttendees }
     * 
     */
    public AudioOnlyType.LimitedAccessAttendees createAudioOnlyTypeLimitedAccessAttendees() {
        return new AudioOnlyType.LimitedAccessAttendees();
    }

    /**
     * Create an instance of {@link CreateTeleconferenceSessionResponse }
     * 
     */
    public CreateTeleconferenceSessionResponse createCreateTeleconferenceSessionResponse() {
        return new CreateTeleconferenceSessionResponse();
    }

    /**
     * Create an instance of {@link SetTeleconferenceSession }
     * 
     */
    public SetTeleconferenceSession createSetTeleconferenceSession() {
        return new SetTeleconferenceSession();
    }

    /**
     * Create an instance of {@link TeleconfInstanceType }
     * 
     */
    public TeleconfInstanceType createTeleconfInstanceType() {
        return new TeleconfInstanceType();
    }

    /**
     * Create an instance of {@link ScheduleType }
     * 
     */
    public ScheduleType createScheduleType() {
        return new ScheduleType();
    }

    /**
     * Create an instance of {@link TeleconfType }
     * 
     */
    public TeleconfType createTeleconfType() {
        return new TeleconfType();
    }

    /**
     * Create an instance of {@link GetTeleconferenceSession }
     * 
     */
    public GetTeleconferenceSession createGetTeleconferenceSession() {
        return new GetTeleconferenceSession();
    }

    /**
     * Create an instance of {@link AttendeeOptionsType }
     * 
     */
    public AttendeeOptionsType createAttendeeOptionsType() {
        return new AttendeeOptionsType();
    }

    /**
     * Create an instance of {@link MetaDataType }
     * 
     */
    public MetaDataType createMetaDataType() {
        return new MetaDataType();
    }

    /**
     * Create an instance of {@link AudioOnlyInstanceType }
     * 
     */
    public AudioOnlyInstanceType createAudioOnlyInstanceType() {
        return new AudioOnlyInstanceType();
    }

    /**
     * Create an instance of {@link AccessControlType }
     * 
     */
    public AccessControlType createAccessControlType() {
        return new AccessControlType();
    }

    /**
     * Create an instance of {@link RepeatType }
     * 
     */
    public RepeatType createRepeatType() {
        return new RepeatType();
    }

    /**
     * Create an instance of {@link AudioOnlyInstanceType.LimitedAccessAttendees }
     * 
     */
    public AudioOnlyInstanceType.LimitedAccessAttendees createAudioOnlyInstanceTypeLimitedAccessAttendees() {
        return new AudioOnlyInstanceType.LimitedAccessAttendees();
    }

    /**
     * Create an instance of {@link SetTeleconferenceSessionResponse }
     * 
     */
    public SetTeleconferenceSessionResponse createSetTeleconferenceSessionResponse() {
        return new SetTeleconferenceSessionResponse();
    }

    /**
     * Create an instance of {@link AttendeeType }
     * 
     */
    public AttendeeType createAttendeeType() {
        return new AttendeeType();
    }

}
