//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.28 at 03:46:38 PM GMT+05:00 
//


package com.webex.schemas._2002._06.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for osType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="osType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="WIN2K"/>
 *     &lt;enumeration value="WINNT"/>
 *     &lt;enumeration value="WIN9X"/>
 *     &lt;enumeration value="LINUX"/>
 *     &lt;enumeration value="HPUX"/>
 *     &lt;enumeration value="AIX"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum OsType {

    @XmlEnumValue("WIN2K")
    WIN_2_K("WIN2K"),
    WINNT("WINNT"),
    @XmlEnumValue("WIN9X")
    WIN_9_X("WIN9X"),
    LINUX("LINUX"),
    HPUX("HPUX"),
    AIX("AIX");
    private final String value;

    OsType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsType fromValue(String v) {
        for (OsType c: OsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
